#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/common_project?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
#    username: maitianer
#    password: maitianer
#    driver-class-name: com.mysql.jdbc.Driver
